package license

import (
	"crypto/ed25519"
	"errors"
	"fmt"
	"time"

	skcrypto "github.com/Laaaaksh/seatkey/internal/crypto"
	"github.com/Laaaaksh/seatkey/internal/store"
)

var (
	// ErrNotFound is returned when the license key or device isn't found.
	ErrNotFound = store.ErrNotFound
	// ErrDeviceLimit is returned when activating a new device would exceed
	// the license's seat limit.
	ErrDeviceLimit = errors.New("device limit reached")
	// ErrLicenseStatus is returned when the license is revoked or expired.
	ErrLicenseStatus = errors.New("license is not active")
)

// offlineHorizon is how far in the future an offline activation is valid when
// the license itself has no expiry. Offline tokens can never be remotely
// revoked once issued (there is no server round-trip to check), so this is
// only ever as safe as the license's own expiry date; SECURITY.md documents
// this trade-off explicitly.
const offlineHorizon = 100 * 365 * 24 * time.Hour

// Notifier is implemented by internal/webhook.Sender. Kept as an interface
// here so this package never imports net/http.
type Notifier interface {
	Notify(event string, data map[string]any)
}

type noopNotifier struct{}

func (noopNotifier) Notify(string, map[string]any) {}

// Service implements Seatkey's licensing rules on top of a Store, signing
// every issued token with the server's Ed25519 key.
type Service struct {
	store    *store.Store
	priv     ed25519.PrivateKey
	pub      ed25519.PublicKey
	notifier Notifier
	now      func() time.Time
}

// NewService builds a Service backed by s, signing tokens with priv/pub.
func NewService(s *store.Store, priv ed25519.PrivateKey, pub ed25519.PublicKey) *Service {
	return &Service{store: s, priv: priv, pub: pub, notifier: noopNotifier{}, now: time.Now}
}

// SetNotifier installs n to receive activation/deactivation events. A nil
// Notifier is ignored, leaving the previous (or default no-op) notifier.
func (s *Service) SetNotifier(n Notifier) {
	if n != nil {
		s.notifier = n
	}
}

// PublicKey returns the server's Ed25519 public key, for clients to verify
// signed tokens against (also served at GET /v1/pubkey).
func (s *Service) PublicKey() ed25519.PublicKey { return s.pub }

// Activate enforces the license's seat limit and issues a signed, cacheable
// token for deviceID. Re-activating an already-active device is idempotent
// and always succeeds (it just refreshes the token), so a client can safely
// call this on every app startup.
func (s *Service) Activate(key, deviceID, deviceName string) (skcrypto.Envelope, error) {
	return s.activate(key, deviceID, deviceName, false)
}

// OfflineActivate is the server side of the offline-activation flow: an
// admin pastes in a request generated by an air-gapped client and gets back
// a signed envelope that client can verify forever using only the server's
// public key, no network required.
func (s *Service) OfflineActivate(key, deviceID, deviceName string) (skcrypto.Envelope, error) {
	return s.activate(key, deviceID, deviceName, true)
}

func (s *Service) activate(key, deviceID, deviceName string, offline bool) (skcrypto.Envelope, error) {
	lic, err := s.store.GetLicenseByKey(key)
	if err != nil {
		return skcrypto.Envelope{}, err
	}

	now := s.now()
	if status := lic.Status(now); status != "active" {
		return skcrypto.Envelope{}, fmt.Errorf("%w: %s", ErrLicenseStatus, status)
	}

	dev, err := s.store.GetActiveDevice(lic.ID, deviceID)
	switch {
	case errors.Is(err, store.ErrNotFound):
		count, cerr := s.store.ActiveDeviceCount(lic.ID)
		if cerr != nil {
			return skcrypto.Envelope{}, cerr
		}
		if count >= lic.MaxDevices {
			return skcrypto.Envelope{}, ErrDeviceLimit
		}
		if dev, err = s.store.ActivateDevice(lic.ID, deviceID, deviceName); err != nil {
			return skcrypto.Envelope{}, err
		}
		s.notify("activation", lic, dev)
	case err != nil:
		return skcrypto.Envelope{}, err
	default:
		if terr := s.store.TouchDevice(dev.ID); terr != nil {
			return skcrypto.Envelope{}, terr
		}
	}

	seats, err := s.store.ActiveDeviceCount(lic.ID)
	if err != nil {
		return skcrypto.Envelope{}, err
	}

	return s.sign(lic, deviceID, seats, now, offline)
}

// Validate refreshes a signed token for a device that is already active on
// this license, without creating a new activation. Use this for a periodic
// check-in; use Activate for first run.
func (s *Service) Validate(key, deviceID string) (skcrypto.Envelope, error) {
	lic, err := s.store.GetLicenseByKey(key)
	if err != nil {
		return skcrypto.Envelope{}, err
	}

	now := s.now()
	if status := lic.Status(now); status != "active" {
		return skcrypto.Envelope{}, fmt.Errorf("%w: %s", ErrLicenseStatus, status)
	}

	dev, err := s.store.GetActiveDevice(lic.ID, deviceID)
	if err != nil {
		return skcrypto.Envelope{}, err
	}
	if err := s.store.TouchDevice(dev.ID); err != nil {
		return skcrypto.Envelope{}, err
	}

	seats, err := s.store.ActiveDeviceCount(lic.ID)
	if err != nil {
		return skcrypto.Envelope{}, err
	}
	return s.sign(lic, deviceID, seats, now, false)
}

// Deactivate frees the seat held by deviceID so another device can activate.
func (s *Service) Deactivate(key, deviceID string) error {
	lic, err := s.store.GetLicenseByKey(key)
	if err != nil {
		return err
	}
	if err := s.store.DeactivateDevice(lic.ID, deviceID); err != nil {
		return err
	}
	s.notify("deactivation", lic, store.Device{DeviceID: deviceID})
	return nil
}

func (s *Service) sign(lic store.License, deviceID string, seatsUsed int, now time.Time, offline bool) (skcrypto.Envelope, error) {
	validUntil := now.Add(OnlineGracePeriod)
	if offline {
		validUntil = now.Add(offlineHorizon)
	}
	if lic.ExpiresAt != nil && lic.ExpiresAt.Before(validUntil) {
		validUntil = *lic.ExpiresAt
	}

	tok := Token{
		LicenseKey:   lic.Key,
		Product:      lic.ProductName,
		CustomerName: lic.CustomerName,
		DeviceID:     deviceID,
		SeatsMax:     lic.MaxDevices,
		SeatsUsed:    seatsUsed,
		Status:       lic.Status(now),
		IssuedAt:     now,
		ValidUntil:   validUntil,
		LicenseExp:   lic.ExpiresAt,
		Offline:      offline,
	}
	return skcrypto.Sign(s.priv, tok)
}

func (s *Service) notify(event string, lic store.License, dev store.Device) {
	s.notifier.Notify(event, map[string]any{
		"event":         event,
		"license_key":   lic.Key,
		"product":       lic.ProductName,
		"customer_name": lic.CustomerName,
		"device_id":     dev.DeviceID,
		"timestamp":     s.now().UTC(),
	})
}
